name: Test Common Custom User Data Gradle Plugin on GHA
on:
    workflow_dispatch:
      inputs:
        branch:
          description: "CCUD Gradle branch to test"
          required: false
          default: "main"
    push:
        paths:
        - ".github/workflows/test_ccud_gradle.yml"
jobs:
    test_ccud_gradle:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                repository: gradle/common-custom-user-data-gradle-plugin
                ref: ${{ github.event.inputs.branch || 'main' }}

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: Set up Gradle
              uses: gradle/actions/setup-gradle@v4
              with:
                  develocity-access-key: ${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}

            - name: Disable signing on CI
              id: disable_signing
              run: sed -i 's/isRequired = providers.environmentVariable("CI").isPresent/isRequired = false/' build.gradle.kts

            - name: Publish to maven local
              id: publish_to_maven_local
              run: ./gradlew clean publishToMavenLocal -Dgradle.cache.remote.push=false

            - name: Modify the project to use the local plugin
              id: modify_project
              run: |
                sed -i '1i\
                  pluginManagement {\
                  repositories {\
                  mavenLocal()\
                  gradlePluginPortal()\
                  mavenCentral()\
                }}\
                ' settings.gradle.kts
                sed -i -E 's/(id\("com.gradle.common-custom-user-data-gradle-plugin"\) version )"2[0-9\.]*"/\1"2+"/' settings.gradle.kts

            - name: Run a build with the local plugin
              id: run_build_with_local_plugin
              run: ./gradlew clean build -i -Dgradle.cache.remote.push=false
